[package]
name = "piko-repl"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "piko-repl"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
piko-core = { workspace = true }

