[package]
name = "piko-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "piko_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde-lexpr = "0.1.3"
lexpr = "0.2.7"
